Fix compilation error on macos due to sprintf
On macos, [-Werror,-Wdeprecated-declarations] will be triggered.

Since MainEntry.cpp includes boost program_options.h,
which leads to
converter_lexical_streams.hpp, and this file uses 'sprintf',
and same thing happens to stdio.h
/Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here