WIP: compile wide_integer fail
```
/home/fuzhe/projects/tics/libs/libcommon/include/common/wide_integer_impl.h: In instantiation of ‘static constexpr wide::integer<Bits, Signed> wide::integer<Bits, Signed>::_impl::multiply(const wide::integer<Bits, Signed>&, const T&) [with T = wide::integer<256, int>; long unsigned int Bits = 256; Signed = int]’:
/home/fuzhe/projects/tics/libs/libcommon/include/common/wide_integer_impl.h:650:31:   required from ‘static constexpr auto wide::integer<Bits, Signed>::_impl::operator_star(const wide::integer<Bits, Signed>&, const T&) [with T = wide::integer<256, int>; long unsigned int Bits = 256; Signed = int]’
/home/fuzhe/projects/tics/libs/libcommon/include/common/wide_integer_impl.h:1221:100:   required from ‘constexpr std::common_type_t<wide::integer<Bits, Signed>, wide::integer<Bits2, Signed2> > wide::operator*(const wide::integer<Bits, Signed>&, const wide::integer<Bits2, Signed2>&) [with long unsigned int Bits = 256; Signed = int; long unsigned int Bits2 = 256; Signed2 = int; std::common_type_t<wide::integer<Bits, Signed>, wide::integer<Bits2, Signed2> > = wide::integer<256, int>]’
/home/fuzhe/projects/tics/libs/libcommon/include/common/wide_integer_impl.h:1227:20:   required from ‘constexpr std::common_type_t<Arithmetic, Arithmetic2> wide::operator*(const Arithmetic&, const Arithmetic2&) [with Arithmetic = wide::integer<256, int>; Arithmetic2 = int; <template-parameter-1-3> = void; std::common_type_t<Arithmetic, Arithmetic2> = wide::integer<256, int>]’
/home/fuzhe/projects/tics/dbms/src/Common/Decimal.h:205:39:   required from here
/home/fuzhe/projects/tics/libs/libcommon/include/common/wide_integer_impl.h:501:22: error: conversion from ‘const wide::integer<256, int>’ to ‘HalfType {aka __int128 unsigned}’ is ambiguous
             HalfType b01 = rhs;
                      ^~~
```